site_name: AppRun Docs
repo_url: https://github.com/apprunjs/apprun-docs
edit_uri: edit/master/docs/
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  favicon: assets/favicon.ico
  logo: assets/logo.png
  features:
    - navigation.sections

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.highlight
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.snippets

extra_css:
  - assets/vendor/codemirror/codemirror.css
  - assets/style.css
  -
extra_javascript:
  - assets/vendor/codemirror/codemirror.js
  - assets/vendor/codemirror/mode/javascript/javascript.js
  - assets/vendor/codemirror/mode/xml/xml.js
  - assets/vendor/codemirror/mode/jsx/jsx.js
  - assets/apprun-play.js

google_analytics:
  - UA-123786786-1
  - auto

nav:
  - Concepts:
    - Architecture:
      - Overview: architecture.md
      - State Management: state-management.md
      - Event Pubsub: event-pubsub.md
      - Component: component.md
      - Reactivity: reactivity.md
    - Examples:
      - Microservice wirh Dapr: architecture-ideas/dapr.md
      - Serverless App Using Firebase: architecture-ideas/firebase-app.md
      - Database and Websocket: architecture-ideas/db-websocket.md
      - Webassembly app with Rust: architecture-ideas/rust-app.md
      - State Machine: architecture-ideas/state-machine.md
  - Getting started:
    - Installation: installation.md
    - Quick Start: tutorial.md
  - Single Page Apps:
    - Creating Project: spa.md
    - Routing: routing.md
  - View Pattern:
    - JSX: view-patterns.md
    - Directive: directive.md
    - 3rd Party Intergration: 3rd-party-libs.md
  - Advanced:
    - CLI in Console: cli-in-console.md
    - Dev Server: dev-server.md
    - Server Side Rendering: ssr.md
    - Strong Typing: strong-typing.md
    - Unit Testing: unit-testing.md
  - Resources: resources.md