site_name: AppRun Docs
repo_url: https://github.com/apprunjs/apprun-docs
edit_uri: edit/master/docs/
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  favicon: assets/favicon.ico
  logo: assets/logo.png
  features:
    - navigation.sections

copyright: Copyright &copy; 2016 - 2021 Yiyi Sun

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.highlight
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.snippets:
      base_path:
        docs/_src
      check_paths: true

extra_css:
  - assets/vendor/codemirror/codemirror.css

extra_javascript:
  - assets/vendor/codemirror/codemirror.js
  - assets/vendor/codemirror/mode/javascript/javascript.js
  - assets/vendor/codemirror/mode/xml/xml.js
  - assets/vendor/codemirror/mode/jsx/jsx.js
  - assets/apprun-play.js

extra:
  analytics:
    provider: google
    property: UA-123786786-1

nav:
  - Home: index.md
  - Concepts:
    - Architecture:
      - Overview: architecture.md
      - Event Pubsub: event-pubsub.md
      - State Management: state-management.md
      - Component: component.md
      - Reactivity: reactivity.md
    - Examples:
      - Microservice wirh Dapr: architecture-ideas/dapr.md
      - Serverless App Using Firebase: architecture-ideas/firebase-app.md
      - Database and Websocket: architecture-ideas/db-websocket.md
      - Webassembly app with Rust: architecture-ideas/rust-app.md
      - State Machine: architecture-ideas/state-machine.md
      - Showcase: showcase.md
  - Getting started:
    - Installation: getting-started.md
    - Tutorial: tutorial.md
  - AppRun Site:
    - Create: apprun-site.md
    - Build: apprun-site-build.md
    - Client-Side Rendering: apprun-site-csr.md
    - Server-Side Rendering: apprun-site-ssr.md
    - Static Web Site: apprun-site-static.md
    - Configurations: apprun-site-config.md
  - View Pattern:
    - JSX: view-patterns.md
    - Directive: directive.md
    - SVG: svg.md
    - 3rd Party Intergration: 3rd-party-libs.md
  - Advanced:
    - Dev Tools: cli-in-console.md
    - Strong Typing: strong-typing.md
    - Unit Testing: unit-testing.md
    - Notebooks: notebooks.md
    - Use with React: react.md
  - Resources: resources.md
  - About: about.md